name: Pylint
on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pylint
        run: sudo apt-get install pylint
      - name: Run pylint
        run: pylint --rcfile=../../library/.pylintrc .
