name : automated test

on:
  pull_request:
    - develop
    - main
  push:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os : [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10"]
  
  name : Test
  runs-on: ${{ matrix.os }}

  steps :
    - name : Checkout code
      uses : actions/checkout@v3

    - name : Set up Python
      uses : actions/setup@v4
      with :
        python-version: ${{ matrix.python-version}}

    - name : Install dependencies
      run : python -m pip install pytest

    - name : Run tests
      run: pytest